<?php /** @var \Walkwizus\MeilisearchMerchandising\Block\Adminhtml\Category\Tree $block */ ?>
<div id="merch-category-tree"></div>
<script>
    requirejs([
        'jquery',
        'jsTree'
    ], function($) {
        $('#merch-category-tree').jstree({
            'plugins': ['wholerow'],
            'core': {
                'multiple': false,
                'data': <?= $block->getCategoryTree() ?>
            }
        }).on('select_node.jstree', function(node, selected) {
            let categoryId = selected.node.id;
            $.ajax('<?= $block->getAjaxUrl() ?>', {
                type: 'POST',
                data: {
                    form_key: window.FORM_KEY,
                    category_id: categoryId
                },
                dataType: 'json',
                showLoader: true,
                success: function(r) {
                    $('#category_id').val(categoryId);
                    if (r.length > 0) {
                        $('#query-builder').queryBuilder('setRules', $.parseJSON(r));
                    } else {
                        $('#query-builder').queryBuilder('setRules', [{empty: true}]);
                    }
                }
            });
        });
    });
</script>
