<?php /** @var \Walkwizus\MeilisearchMerchandising\Block\Adminhtml\Category\Tree $block */ ?>
<?php if ($block->getStoreId()) : ?>
<div id="merch-category-tree"></div>
<script type="text/x-magento-init">
    {
        "#merch-category-tree": {
            "Walkwizus_MeilisearchMerchandising/js/category/tree": {
                "categoryTree": <?= $block->getCategoryTree() ?>,
                "loadRuleUrl": "<?= $block->getLoadRuleUrl() ?>"
            }
        }
    }
</script>
<?php endif; ?>
