<?php /** @var \Walkwizus\MeilisearchMerchandising\Block\Adminhtml\Category\Query\Builder $block */?>
<?php if (!$block->getStoreId()) : ?>
<div class="notices-wrapper">
    <div class="messages">
        <div class="message">
            <strong><?= __('To configure category merchandising, please select a store') ?></strong>
        </div>
    </div>
</div>
<?php else : ?>
<form id="category-merchandising-form" action="<?= $block->getSaveRuleUrl() ?>" method="post">
    <button type="submit" id="save-rule" title="<?= __('Save Rule') ?>" class="save primary">
        <span><?= __('Save Rule') ?></span>
    </button>
    <button type="button" id="apply-rule" title="<?= __('Apply Rule') ?>" class="save secondary">
        <span><?= __('Apply Rule') ?></span>
    </button>
    <button type="button" id="delete-rule" title="<?= __('Delete Rule') ?>" class="save secondary">
        <span><?= __('Delete Rule') ?></span>
    </button>
    <input type="hidden" id="category_id" name="category_id"/>
    <div id="query-builder"></div>
</form>
<script id="category-merchandising-preview-template" type="text/x-magento-template">
    <div class="product-list-container">
        <div class="product-card" id="product-<%- data.id %>">
            <div class="product-card-img">
                <label class="stock bg-success">In Stock</label>
                <img src="<?= $block->getProductMediaUrl() ?>/<%- data.image %>" alt="<%- data.name %>" />
            </div>
            <div class="product-card-body">
                <p class="product-brand"><%- data.sku %></p>
                <h5 class="product-name">
                    <a href="javascript:;">
                        <%- data.name %>
                    </a>
                </h5>
                <div>
                    <span class="selling-price"><%- data.price_0 %></span>
                </div>
                <div class="mt-2">
                    <a href="#" data-product-id="<%- data.id %>" class="promote-product">
                        <i class="fa fa-heart"></i>Boost
                    </a>
                </div>
            </div>
        </div>
    </div>
</script>
<div id="category-promoted-products"></div>
<div id="category-merchandising-preview"></div>
<button id="load-more"><?= __('Load More') ?></button>
<div id="chooser-sku-modal">
    <div class="modal-body-content"></div>
</div>
<script type="text/x-magento-init">
    {
        "#category-merchandising-form": {
            "Walkwizus_MeilisearchMerchandising/js/category/query/builder": {
                "queryBuilderContainer": "#query-builder",
                "filters": <?= $block->getFilters() ?>,
                "previewUrl": "<?= $block->getPreviewUrl() ?>",
                "productChooserUrl": "<?= $block->getProductChooserUrl() ?>",
                "categoryChooserUrl": "<?= $block->getCategoryChooserUrl() ?>",
                "promoteProductUrl": "<?= $block->getPromoteProductUrl() ?>",
                "deleteRuleUrl": "<?= $block->getDeleteRuleUrl() ?>",
                "storeId": "<?= $block->getStoreId() ?>"
            }
        }
    }
</script>
<?php endif; ?>
