<?php /** @var \Walkwizus\MeilisearchMerchandising\Block\Adminhtml\Category\Query\Builder $block */?>
<?php if (!$block->getStoreId()) : ?>
<div class="notices-wrapper">
    <div class="messages">
        <div class="message">
            <strong><?= __('To configure category merchandising, please select a store') ?></strong>
        </div>
    </div>
</div>
<?php else : ?>
<form id="category-merchandising-form" action="<?= $block->getSaveRuleUrl() ?>" method="post">
    <button type="submit" id="save-rule" title="<?= __('Save Rule') ?>" class="save primary">
        <span><?= __('Save Rule') ?></span>
    </button>
    <button type="button" id="apply-rule" title="<?= __('Apply Rule') ?>" class="save secondary">
        <span><?= __('Apply Rule') ?></span>
    </button>
    <button type="button" id="delete-rule" title="<?= __('Apply Rule') ?>" class="save secondary">
        <span><?= __('Delete Rule') ?></span>
    </button>
    <input type="hidden" id="category_id" name="category_id"/>
    <div id="query-builder"></div>
</form>
<script id="category-merchandising-preview-template" type="text/x-magento-template">
    <div class="product-list-container">
        <div class="product-image">
            <img src="<?= $block->getProductMediaUrl() ?>/<%- data.image %>" alt="<%- data.name %>" />
        </div>
        <div class="product-information">
            <div class="product-name"><%- data.name %></div>
            <div class="product-sku"><%- data.sku %></div>
            <div class="product-price"><%- data.price_0 %></div>
        </div>
    </div>
</script>
<div id="category-merchandising-preview"></div>
<div id="modal">
    <div class="modal-body-content">
        content
    </div>
</div>
<script type="text/x-magento-init">
    {
        "#category-merchandising-form": {
            "Walkwizus_MeilisearchMerchandising/js/category/query/builder": {
                "queryBuilderContainer": "#query-builder",
                "filters": <?= $block->getFilters() ?>,
                "previewUrl": "<?= $block->getPreviewUrl() ?>",
                "productChooserUrl": "<?= $block->getProductChooserUrl() ?>",
                "storeId": "<?= $block->getStoreId() ?>"
            }
        }
    }
</script>
<?php endif; ?>
